include(pico-keys-sdk/cmake/dict.cmake)

dict(SET led_driver 0xcb_helios led_ws2812)
dict(SET led_driver adafruit_feather_rp2040_usb_host led_pico)
dict(SET led_driver adafruit_feather_rp2040 led_ws2812)
dict(SET led_driver adafruit_itsybitsy_rp2040 led_ws2812)
dict(SET led_driver adafruit_kb2040 led_ws2812)
dict(SET led_driver adafruit_macropad_rp2040 led_ws2812)
dict(SET led_driver adafruit_qtpy_rp2040 led_ws2812)
dict(SET led_driver adafruit_trinkey_qt2040 led_ws2812)
dict(SET led_driver amethyst_fpga led_pico)
dict(SET led_driver archi led_ws2812)
dict(SET led_driver arduino_nano_rp2040_connect led_pico)
dict(SET led_driver cytron_maker_pi_rp2040 led_ws2812)
dict(SET led_driver datanoisetv_rp2040_dsp led_pico)
dict(SET led_driver eetree_gamekit_rp2040 led_pico)
dict(SET led_driver garatronic_pybstick26_rp2040 led_pico)
dict(SET led_driver ilabs_challenger_rp2350_bconnect led_ws2812)
dict(SET led_driver ilabs_challenger_rp2350_wifi_ble led_pico)
dict(SET led_driver ilabs_opendec02 led_pico)
dict(SET led_driver melopero_perpetuo_rp2350_lora led_pico)
dict(SET led_driver melopero_shake_rp2040 led_ws2812)
dict(SET led_driver metrotech_xerxes_rp2040 led_pico)
dict(SET led_driver net8086_usb_interposer led_pico)
dict(SET led_driver nullbits_bit_c_pro led_pico) # rgb
dict(SET led_driver phyx_rick_tny_rp2350 led_ws2812)
dict(SET led_driver pi-plates_micropi led_pico)
dict(SET led_driver pico led_pico)
dict(SET led_driver pico_w led_cyw43)
dict(SET led_driver pico2 led_pico)
dict(SET led_driver pimoroni_badger2040 led_pico)
dict(SET led_driver pimoroni_interstate75 led_pico) # rgb
dict(SET led_driver pimoroni_motor2040 led_ws2812)
dict(SET led_driver pimoroni_pga2350 led_pico)
dict(SET led_driver pimoroni_pico_plus2_rp2350 led_pico)
dict(SET led_driver pimoroni_picolipo_4mb led_pico)
dict(SET led_driver pimoroni_picolipo_16mb led_pico)
dict(SET led_driver pimoroni_picosystem led_pico) # rgb
dict(SET led_driver pimoroni_plasma2040 led_pico) # rgb
dict(SET led_driver pimoroni_plasma2350 led_pico) # rgb
dict(SET led_driver pimoroni_servo2040 led_ws2812)
dict(SET led_driver pimoroni_tiny2040 led_pimoroni)
dict(SET led_driver pimoroni_tiny2040_2mb led_pimoroni)
dict(SET led_driver pimoroni_tiny2350 led_pimoroni)
dict(SET led_driver pololu_3pi_2040_robot led_pico)
dict(SET led_driver pololu_zumo_2040_robot led_pico)
dict(SET led_driver seeed_xiao_rp2040 led_ws2812)
dict(SET led_driver seeed_xiao_rp2350 led_ws2812)
dict(SET led_driver solderparty_rp2040_stamp led_ws2812)
dict(SET led_driver solderparty_rp2040_stamp_carrier led_ws2812)
dict(SET led_driver solderparty_rp2040_stamp_round_carrier led_ws2812)
dict(SET led_driver sparkfun_micromod led_pico)
dict(SET led_driver sparkfun_promicro led_ws2812)
dict(SET led_driver sparkfun_promicro_rp2350 led_ws2812)
dict(SET led_driver sparkfun_thingplus led_ws2812)
dict(SET led_driver switchscience_picossci2_conta_base led_pico)
dict(SET led_driver switchscience_picossci2_dev_board led_pico)
dict(SET led_driver switchscience_picossci2_rp2350_breakout led_pico)
dict(SET led_driver switchscience_picossci2_tiny led_pico)
dict(SET led_driver tinycircuits_thumby_color_rp2350 led_pico)
dict(SET led_driver vgaboard led_pico)
dict(SET led_driver waveshare_rp2040_one led_ws2812)
dict(SET led_driver waveshare_rp2040_plus_4mb led_pico)
dict(SET led_driver waveshare_rp2040_plus_16mb led_pico)
dict(SET led_driver waveshare_rp2040_zero led_ws2812)
dict(SET led_driver weact_studio_rp2040_2mb led_pico)
dict(SET led_driver weact_studio_rp2040_4mb led_pico)
dict(SET led_driver weact_studio_rp2040_8mb led_pico)
dict(SET led_driver weact_studio_rp2040_16mb led_pico)
dict(SET led_driver wiznet_w5100s_evb_pico led_pico)
