macro(configure_bool_option option_name define_name enabled_msg disabled_msg)
    if(${option_name})
        if(NOT "${define_name}" STREQUAL "")
            add_compile_definitions(${define_name}=1)
        endif()
        message(STATUS "${enabled_msg}")
    else()
        if(NOT "${define_name}" STREQUAL "")
            add_compile_definitions(${define_name}=0)
        endif()
        message(STATUS "${disabled_msg}")
    endif()
endmacro()

